import { useEffect, useState } from "react";
import { ExternalLink, FileWarning, Paperclip } from "lucide-react";
import type { FieldMeta } from "../../api/types";
import { Checkbox, Select, TextArea, TextInput } from "../../components/Field";
import { ReferencePicker } from "./ReferencePicker";
import { FilePicker } from "./FilePicker";
import { MultiFileEditor } from "./MultiFileEditor";
import { resolveFilerFile, type FilerLookup } from "./format";

/* One input per canonical field type (docs/arc.MD §3.9). Values are held
   as strings (or boolean) and sent as-is — admin's own _coerce.py turns
   them into the real Python/DB types, so the form never has to guess.

   DATETIME note: values are displayed and submitted as UTC wall time (the
   stored value sliced to YYYY-MM-DDTHH:mm); the server treats a naive
   datetime as UTC, so the round-trip doesn't drift. */

interface Props {
  field: FieldMeta;
  value: string | boolean;
  onChange: (value: string | boolean) => void;
  disabled?: boolean;
  /** The current table's parent table (TableSchema.parent_table), needed
   *  only for a REFERENCE_UUID field — that's the child's auto-injected
   *  `parent` system field, whose FK target psqldb fills in at migration
   *  time and never exposes on the Field itself. */
  parentTable?: string | null;
  error?: string;
}

export function FieldInput({ field, value, onChange, disabled, parentTable, error }: Props) {
  const t = field.type;

  // REFERENCE_UUID is a child table's `parent` system field — same picker
  // as REFERENCE, just resolved via parentTable instead of field.target
  // (which is always null on this field type).
  if (t === "REFERENCE" || t === "REFERENCE_UUID") {
    return (
      <ReferencePicker
        field={field}
        value={String(value ?? "")}
        onChange={onChange}
        disabled={disabled}
        targetTable={t === "REFERENCE_UUID" ? parentTable : undefined}
      />
    );
  }

  if (t === "BOOLEAN") {
    return (
      <Checkbox
        label={value === true || value === "true" ? "True" : "False"}
        checked={value === true || value === "true"}
        onChange={(e) => onChange(e.target.checked)}
        disabled={disabled}
      />
    );
  }

  if (t === "SELECT") {
    return (
      <Select value={String(value ?? "")} onChange={(e) => onChange(e.target.value)} disabled={disabled} error={error}>
        <option value="">— none —</option>
        {(field.options ?? []).map((o) => (
          <option key={o} value={o}>
            {o}
          </option>
        ))}
      </Select>
    );
  }

  if (t === "MULTIFILE") {
    return <MultiFileEditor raw={String(value ?? "")} onChange={onChange} disabled={disabled} error={error} />;
  }

  if (t === "TEXT" || t === "JSON") {
    return (
      <TextArea
        mono={t === "JSON"}
        rows={t === "JSON" ? 5 : 3}
        value={String(value ?? "")}
        onChange={(e) => onChange(e.target.value)}
        disabled={disabled}
        placeholder={t === "JSON" ? '{ "key": "value" }' : undefined}
        error={error}
      />
    );
  }

  if (t === "FILE") {
    // A filer file_id — a plain VARCHAR(32) column, always server-
    // generated by filer's own upload() (never user-typed by hand in
    // practice) — a REFERENCE-picker-style search-by-filename combobox
    // over the real filerfile table (FilePicker), same pattern a real
    // REFERENCE field already gets, rather than a raw text box asking
    // someone to know/paste an opaque id. FilePreview below still adds
    // servability/status + a real "open" link FilePicker doesn't show.
    return (
      <div className="flex flex-col gap-1.5">
        <FilePicker value={String(value ?? "")} onChange={onChange} disabled={disabled} error={error} />
        <FilePreview fileId={String(value ?? "")} />
      </div>
    );
  }

  const typeAttr =
    t === "INT" || t === "FLOAT" || t === "DECIMAL"
      ? "number"
      : t === "DATE"
        ? "date"
        : t === "TIME"
          ? "time"
          : t === "DATETIME"
            ? "datetime-local"
            : t === "EMAIL"
              ? "email"
              : "text";

  return (
    <TextInput
      type={typeAttr}
      step={t === "FLOAT" || t === "DECIMAL" ? "any" : undefined}
      maxLength={field.length ?? undefined}
      value={String(value ?? "")}
      onChange={(e) => onChange(e.target.value)}
      disabled={disabled}
      placeholder={placeholderFor(field)}
      error={error}
    />
  );
}

function placeholderFor(field: FieldMeta): string | undefined {
  if (field.type === "REFERENCE") {
    return field.target_field ? `${field.target}.${field.target_field}` : `${field.target} id (uuid)`;
  }
  if (field.type === "PHONE") return "+1 555 123 4567";
  return undefined;
}

/** Small resolved-file affordance for a FILE field — shows the real
 *  filename (and a link, when servable) instead of leaving the raw
 *  file_id as the only thing on screen. */
function FilePreview({ fileId }: { fileId: string }) {
  const [lookup, setLookup] = useState<FilerLookup | null | undefined>(undefined);

  useEffect(() => {
    if (!fileId) {
      setLookup(undefined);
      return;
    }
    let cancelled = false;
    setLookup(undefined);
    resolveFilerFile(fileId).then((r) => {
      if (!cancelled) setLookup(r);
    });
    return () => {
      cancelled = true;
    };
  }, [fileId]);

  if (!fileId) return null;
  if (lookup === undefined) return <p className="text-xs text-text-faint">Resolving file…</p>;
  if (lookup === null) {
    return (
      <p className="flex items-center gap-1.5 text-xs text-warning">
        <FileWarning size={13} /> No matching file found for this id.
      </p>
    );
  }
  return (
    <p className="flex items-center gap-1.5 text-xs text-text-muted">
      <Paperclip size={13} className="shrink-0" />
      <span className="truncate">{lookup.filename}</span>
      {lookup.status && lookup.status !== "clean" && <span className="text-text-faint">({lookup.status})</span>}
      {lookup.url && (
        <a href={lookup.url} target="_blank" rel="noreferrer" className="inline-flex shrink-0 items-center gap-0.5 text-accent-600 hover:underline">
          open <ExternalLink size={11} />
        </a>
      )}
    </p>
  );
}

