import type { FieldMeta } from "../../api/types";
import { ReferencePicker } from "./ReferencePicker";

/* One input per canonical field type (docs/arc.MD §3.9). Values are held
   as strings (or boolean) and sent as-is — admin's own _coerce.py turns
   them into the real Python/DB types, so the form never has to guess.

   DATETIME note: values are displayed and submitted as UTC wall time
   (the stored value sliced to YYYY-MM-DDTHH:mm); the server treats a naive
   datetime as UTC, so the round-trip doesn't drift. */

interface Props {
  field: FieldMeta;
  value: string | boolean;
  onChange: (value: string | boolean) => void;
  disabled?: boolean;
  /** The current table's parent table (TableSchema.parent_table), needed
   *  only for a REFERENCE_UUID field — that's the child's auto-injected
   *  `parent` system field, whose FK target psqldb fills in at migration
   *  time and never exposes on the Field itself. */
  parentTable?: string | null;
}

export function FieldInput({ field, value, onChange, disabled, parentTable }: Props) {
  const t = field.type;
  const common = { disabled, className: "input" as const };

  // REFERENCE_UUID is a child table's `parent` system field — same picker
  // as REFERENCE, just resolved via parentTable instead of field.target
  // (which is always null on this field type).
  if (t === "REFERENCE" || t === "REFERENCE_UUID") {
    return (
      <ReferencePicker
        field={field}
        value={String(value ?? "")}
        onChange={onChange}
        disabled={disabled}
        targetTable={t === "REFERENCE_UUID" ? parentTable : undefined}
      />
    );
  }

  if (t === "BOOLEAN") {
    return (
      <label className="bool-input">
        <input
          type="checkbox"
          checked={value === true || value === "true"}
          onChange={(e) => onChange(e.target.checked)}
          disabled={disabled}
        />
        <span className="muted">{value === true || value === "true" ? "True" : "False"}</span>
      </label>
    );
  }

  if (t === "SELECT") {
    return (
      <select
        className="select"
        value={String(value ?? "")}
        onChange={(e) => onChange(e.target.value)}
        disabled={disabled}
      >
        <option value="">— none —</option>
        {(field.options ?? []).map((o) => (
          <option key={o} value={o}>
            {o}
          </option>
        ))}
      </select>
    );
  }

  if (t === "TEXT" || t === "JSON" || t === "MULTIFILE") {
    // MULTIFILE is a plain JSONB array under the hood (identical DDL to
    // JSON — see psqldb/fields.py's own note on this) — same textarea,
    // same raw-JSON editing, just a MULTIFILE-specific placeholder
    // showing the {label, fileid} shape filer actually expects
    // (docs/filer-attachment-storage-proposal.md §4/§6).
    return (
      <textarea
        className="textarea mono"
        rows={t === "JSON" || t === "MULTIFILE" ? 5 : 3}
        value={String(value ?? "")}
        onChange={(e) => onChange(e.target.value)}
        disabled={disabled}
        placeholder={
          t === "JSON"
            ? '{ "key": "value" }'
            : t === "MULTIFILE"
              ? '[{"label": "Contract A", "fileid": "pub_..."}]'
              : undefined
        }
      />
    );
  }

  if (t === "FILE") {
    // A filer file_id — a plain VARCHAR(32) column, always server-
    // generated by filer's own upload() (never user-typed in practice),
    // but still editable here as a raw id for admin/debugging purposes
    // — same posture Data Browser already takes toward every other raw
    // foreign-key-shaped field.
    return (
      <input
        {...common}
        className="input mono"
        type="text"
        maxLength={32}
        value={String(value ?? "")}
        onChange={(e) => onChange(e.target.value)}
        placeholder="file_id (e.g. pub_… / pri_…)"
      />
    );
  }

  const typeAttr =
    t === "INT" || t === "FLOAT" || t === "DECIMAL"
      ? "number"
      : t === "DATE"
        ? "date"
        : t === "TIME"
          ? "time"
          : t === "DATETIME"
            ? "datetime-local"
            : t === "EMAIL"
              ? "email"
              : "text";

  return (
    <input
      {...common}
      type={typeAttr}
      step={t === "FLOAT" || t === "DECIMAL" ? "any" : undefined}
      maxLength={field.length ?? undefined}
      value={String(value ?? "")}
      onChange={(e) => onChange(e.target.value)}
      placeholder={placeholderFor(field)}
    />
  );
}

function placeholderFor(field: FieldMeta): string | undefined {
  if (field.type === "REFERENCE") {
    return field.target_field
      ? `${field.target}.${field.target_field}`
      : `${field.target} id (uuid)`;
  }
  if (field.type === "PHONE") return "+1 555 123 4567";
  return undefined;
}
